### PR TITLE
app.py: Fix syntatical error with print.

### PR DESCRIPTION
**Pull request by brotatos**
Print is now a function call in python3.

Also, you shouldn't be using tabs.

### CODE REVIEW

**Comment by sgricci** [comment]
The print is debug. It has been removed from the development branch (month+ ago). Also, breaks 2.x compatibility.

Converting tabs to spaces is a style issue, and I use tabs.  Feel free to keep your own branch in spaces.

If you send the remove trailing white spaces as its own pull request, I will merge that.

**Comment by brotatos** [comment]
@sgricci How long do you intend to maintain 2.x compatibility?

**Comment by sgricci** [comment]
At least until several popular distros start shipping Python 3 as the default.

I think Ubuntu is slated to make that change in their 14.04 release, unsure of others.

**Comment by brotatos** [comment]
Good to know. I'll start making changes with that in mind.

**Comment by brotatos** [comment]
As for tabs, I really urge you to switch to using spaces. Tabs do not have a universal size while spaces do. Using tabs can result in oddly indented code in different work environments while spaces will maintain their look.

Let me know if you need help switching. I'm curious as to what your development environment is like.

Also, [pep8 suggests that you use spaces instead of tabs.](http://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)

**Comment by sgricci** [comment]
Spaces maintain their look, but are specified in size by the font selection.

Tabs on the other hand allow me and anyone else to set how wide a tab is.  In vim, I set :tabstop=<number> and can have it equivalent to 4 spaces, 2, 8, whatever I prefer.

I don't specifically have a problem with 4 spaces, but my set up is already using tabs and to switch to spaces for one project and lose flexibility seems unworthy of the effort.

**Pull request closed without merging**
